### ISSUE TITLE
Hey would love to chat to you about the mod 

### ISSUE THREAD

**Issue by craig1988** [MatWein/RaumShips#1]
Do you have discord ? Sorry this was the only way I could see to get in touch with you

**Comment by craig1988** [comment]
https://www.curseforge.com/minecraft/mc-mods/starship 

Would you consider adding the stargate ships from this mod if possible if the bigger ones arnt possibly maybe some of the smaller ones like the needle threader and such ?

**Comment by MatWein** [comment]
I added some of the ships, see v1.2.1 (https://github.com/MatWein/RaumShips/releases)

**Comment by craig1988** [comment]
That’s super cool man thanks lol is the any chance of some screen shots as I won’t be able to get on till Tuesday 😂

Thanks Craig

**Comment by craig1988** [comment]
Sorry found them 

Thanks Craig
