### ISSUE TITLE
Stealing

### ISSUE THREAD

**Issue by MrJake222** [MatWein/RaumShips#2]
You think it's okay to copy all my rendering, loading, teleporting and syncing code and *just* use it in your mod? The license clearly states that you *can* use the code, get inspired by it, OpenSource. But not just outright steal it man... Instead of stealing you could just endorse my mod, that your mod is compatible with yours.

https://github.com/MrJake222/AUNIS/blob/master/LICENSE.md

**Comment by MatWein** [comment]
1. I give your repository a star
2. I wrote at the end of my README that the ring transporter comes from your mod
3. I fixed a dozen of bugs in your code
4. I make no money with this stuff. Its only for fun of me and maybe of other people.

So its not just stolen.

**Comment by RedstoneSucht** [comment]
so you admit to having stolen something. You also violated Aunis' license by copying code.

From MrJake222 License at 13th May 2019
> Do whatever you like with the original work, just don't be a dick. Being a dick includes - but is not limited to - the following instances:
>    * Outright copyright infringement - Don't just copy this and change the name.
>    * Selling the unmodified original with no work done what-so-ever, that's REALLY being a dick.
>    * Modifying the original work to contain hidden harmful content. That would make you a PROPER dick.

And your Readme is incomplete. What is with the code from MrJake? You should be ashamed of copying something and integrating it into your own mod.

**Comment by WhiteHatcker** [comment]
Actually, MrJake's License states you can't outright copy it and change the name, you can't sell the unmodified original and I don't see any hidden harmful content. MatWein just added a bit of code from MrJake's project. He also changed the code of the ring transporter, so it is not just copy-paste into his mod.

**Comment by PoltixeTheDerg** [comment]
It isn't just a "bit" it is a large chunk of code taken, and he may have "changed the code" but not nearly enough to be considered not being a dick

**Comment by WhiteHatcker** [comment]
Actually, I agree with you, Brayden.
